services:
  utazon_backend:
    container_name: utazon_backend
    build: .
    environment:
      - PORT=3001
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_USER_IDS=${DISCORD_USER_IDS}
      - RUST_LOG=${RUST_LOG}
    restart: unless-stopped
