services:
  utazon_backend:
    container_name: utazon_backend
    build: .
    environment:
      - PORT=3001
      - MINIO_INTERNAL_ENDPOINT=${MINIO_INTERNAL_ENDPOINT}
      - MINIO_INTERNAL_PORT=${MINIO_INTERNAL_PORT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - RUST_LOG=${RUST_LOG}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
    restart: unless-stopped
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.utazon_backend.rule=Host(`utazon-backend.adrienpelfresne.com`)"
      - "traefik.http.routers.utazon_backend.entrypoints=websecure"
      - "traefik.http.routers.utazon_backend.tls=true"
      - "traefik.http.routers.utazon_backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.utazon_backend.service=utazon_backend"
      - "traefik.http.services.utazon_backend.loadbalancer.server.port=3001"

networks:
  traefik_public:
    external: true
